### ISSUE TITLE
Documentation is missing details regarding slack token

### ISSUE THREAD

**Issue by blindrood** [yutachaos/kube-job-notifier#136]
Hello, nice work here. While I was testing Your solution I stumbled upon and issue with weird errors
```
E0519 11:32:44.789564 1 slack.go:113] Template execute failed missing_scope
E0519 11:32:44.789572 1 controller.go:146] Failed slack n: missing_scope
```
After spending some time debugging, I found out that token requires `files:write` permissions. It'd be nice to have it documented somewhere

**Comment by yutachaos** [comment]
closed 
https://github.com/yutachaos/kube-job-notifier/pull/195
