### ISSUE TITLE
Latest 0.0.22 fails with Get Pod list

### ISSUE THREAD

**Issue by blindrood** [yutachaos/kube-job-notifier#137]
With version 0.0.22 I'm getting
```
E0519 11:32:44.800705 1 controller.go:123] Get pods failed: Failed get pod list jobPodList.Items): []
```
I see that this is coming from latest addition of `func isComplatedJob` <- notice the typo here as well

and this line of code
```
kubeclientset.CoreV1().Pods(job.Namespace).List(context.TODO(), metav1.ListOptions{
```
I'm assuming this TODO is something that breaks code

**Comment by yutachaos** [comment]
Thanks for your issue.
This issue is fixed.
