### ISSUE TITLE
Use a public annotation based on relevant DNS name

### ISSUE THREAD

**Issue by sftim** [yutachaos/kube-job-notifier#188]
Instead of `kube-job-notifier/default-channel`, use an annotation key based on a real DNS name.

For example, buy a domain something like `yutachaos.example` and then use `kube-job-notifier.tools.yutachaos.example/default-channel` etc.

**Comment by sftim** [comment]
@yutachaos would you be willing to fix this if someone else wrote the code?

Also, if you object to a fix, you might want to close this as “not planned”.

**Comment by yutachaos** [comment]
@sftim 
I didn't understand why I had to do this, so I closed it.
If you would like to tell us the reason and make a PR, we would be most welcome.

**Comment by sftim** [comment]
@yutachaos I'm not sure I can make a fix easily (it might mean learning a new programming language).

The reason for using a public name based on real DNS domains is that it prevents a clash. For example, if there are two projects that call themselves `kube-job-notifier` (perhaps one is internal to a company and one is this project), they can be told apart.

It's good practice too; see https://kubernetes.io/docs/reference/labels-annotations-taints/ for how Kubernetes itself namespaces the keys for annotations and labels.
